branches:
  only:
    - master

language: bash

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - repo=fingershock/ruby
  - builddate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - buildrev=$(git rev-parse --short HEAD)

script:
  - docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo:latest         -f Dockerfile-runtime .
  - docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo:latest-builder -f Dockerfile-builder .
  - docker run --rm fingershock/ruby:latest ruby --version
  - ./test/run
  - vertags=$(docker run --rm $repo:latest ruby -e '(0..1).each { |i| puts RUBY_VERSION.split(".")[0..i].join(".") }; puts RUBY_VERSION')

after_success:
  - for ver in $vertags; do docker tag $repo:latest $repo:$ver; docker tag $repo:latest-builder $repo:$ver-builder; done
  - for ver in $vertags; do docker push $repo:$ver; docker push $repo:$ver-builder; done
  - docker push $repo:latest
  - docker push $repo:latest-builder

notifications:
  slack:
    rooms:
      secure: eQHTlEtEzYf9b421Zb9ZPJ1owS9OEp+ei1Qh/apf6+ji21GtosEDpsuZQ7jNp50KdUOwB9ihdaWB/D0SKPE+4QEWfVXhxKjXtnj0mYNo5qc0RbggXbZTmh99zeiZmGUAV/63M6G8pLzeKP/rfVYDGjHDcbpCaqdgw1M9H+SapV+YEZd+Hpp/w1+1fLQNXK5FoTnkRDO/iv2zv4nYvfHRis2EIKeTa3BucfP9eF+4nf+Le7m6hJ8NLvgU5eKFecKGRYPM384IFepfQcNn4wVLBAG2r4HokamYPQbg1pMD28iQlyl+fEOmOj3lDa9oV/pwjX5QgDRX9EpLY3JN+n+GNGBa/09qw+i6MqThNm3AYonDjlUoVwcczVBrnMtgxxLQhZVjVLw38/bsTmHjnB3R+GTjxky4WGE0SvLtQdz532AmkfkugGYg91uQAj/Yjjt8SbHm1lO4cvL7jfcAPUcjDrbQ/NrJVyF6ZtRugBz729tRbevz4ti2IXbC17f2TeQmvaAS/BjcVrOH5u7JGLRQm09wMaJ6W6fGIUQcPApPe7AGJCe3qIA/51npJuqDErRN08fIlGBbpdPH4Axs1iJTfO8gSnBJYnjqBta5TRI7s7Z9WjzBGvriTG6wNgW+IjmtNa4xGvXLiEBQ+Bt5m7Bf1WO5OA7TacFmuTmHm5yZSao=
