branches:
  only:
    - master

language: bash

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - repo=fingershock/ruby
  - builddate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - buildrev=$(git rev-parse --short HEAD)

script:
  - docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo:latest         -f Dockerfile-runtime .
  - docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo:latest-builder -f Dockerfile-builder .
  - docker run --rm $repo:latest ruby --version
  - ./test/run
  - vertags=$(docker run --rm $repo:latest ruby -e '(0..1).each { |i| puts RUBY_VERSION.split(".")[0..i].join(".") }; puts RUBY_VERSION')

after_success:
  - for ver in $vertags; do docker tag $repo:latest $repo:$ver; docker tag $repo:latest-builder $repo:$ver-builder; done
  - for ver in $vertags; do docker push $repo:$ver; docker push $repo:$ver-builder; done
  - docker push $repo:latest
  - docker push $repo:latest-builder

notifications:
  slack:
    rooms:
      secure: oxHg4kT8rTVLyz4UxZ0mf5uubmEyaOZbDr4slP74eI7BTlItr+GOvTHR680OVmlp0PC2ReWpT8CGXh94WHfNSKwQqK5cEaS90xjRR5m2pcWaUUUtGRk26lx0xrSL2Wc3QruyBQDgb9StiUvD1yf13fTfbtdVbRLMCEUtoR9wD5Kv7/harx1514hZCtPgHNsUtwgs9oR10jJTohp0TdsyusH0RKTs90lIKqq8vSiChfkwgiKPY0sWHP9C02uBZ6YWECzXzQbL9HMoznHnSSdgXU3btAdTn0DSKR0uhuRpr4OOmmwk5TQjqpoWL6fKhkXmWg4HTnHJxh0VvgV6sAYqiYq0qIdy5Y1yaiDIA1EmX1RN8xz0x1ZPv99F17A78awkzWnyQV5LGALVsijaQBAENHxjPp7fadlpOBQpbmZWMvXicAAy8OSDbfcAyOA9uk7eZUJ1dBFIv2mOvCaiy4munYeJVhpGIKCIZw+QfcbciGEoLDCfOX5nET2CumMv3sQJClJZ/heWdlFzIuJguaR5Z8QF2pZCB67HddlBjbC4oDvXX2skC6T9WfyzFCgmwDgl5fZIQKFCEal4C/C7Qq8eGlAzkbCAZA+6bxQXps1hm65DFkXtvB0HKhm1ZWd7/hb43VcYEA8Bz8iGEkplTiF4JBlYTOIh+yaDW4YHxeC3ya4=
