FROM fingershock/ruby:latest
MAINTAINER Bryan Talbot <bryan.talbot@ijji.com>

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.docker.dockerfile="Dockerfile-builder" \
      org.label-schema.license="MIT" \
      org.label-schema.name="Docker ruby builder" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-type="git" \
      org.label-schema.vcs-url="https://github.com/iJJi/docker-ruby" \
      org.label-schema.vendor="Ijji, inc."

RUN apk add --no-cache -t build-deps ruby-dev make gcc libc-dev pcre-dev linux-headers g++ git libxml2-dev libxslt-dev zlib-dev

