FROM alpine:3.5
MAINTAINER Bryan Talbot <bryan.talbot@ijji.com>

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.docker.dockerfile="Dockerfile-runtime" \
      org.label-schema.license="MIT" \
      org.label-schema.name="Docker ruby runtime" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-type="git" \
      org.label-schema.vcs-url="https://github.com/iJJi/docker-ruby" \
      org.label-schema.vendor="Ijji, inc."

RUN apk add --no-cache ruby ruby-bigdecimal ruby-io-console ruby-bundler ca-certificates wget libxslt libxml2
WORKDIR /usr/src/app
